### ISSUE TITLE
well.df() yields 'DataFrame' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by leomiquelutti** [agile-geoscience/welly#216]
Dear,

I am using `welly` in Google Colab. After reading and manipulating a las file, I get the following error when trying to convert it to `pandas Dataframe` with `well.df()`:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-27-820e487117e9>](https://localhost:8080/#) in <module>()
----> 1 w.df()

1 frames
[/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py](https://localhost:8080/#) in __getattr__(self, name)
   5485         ):
   5486             return self[name]
-> 5487         return object.__getattribute__(self, name)
   5488 
   5489     def __setattr__(self, name: str, value) -> None:

AttributeError: 'DataFrame' object has no attribute 'dtype'
```

Environment setup was done with:

```
!pip install welly
!pip install lasio
!pip install wellpathpy
```

The file loaded is **KK1.las**, available at https://raw.githubusercontent.com/mardani72/Synthetic_Seismogram/master/KK1.las.

**Comment by EvanBianco** [comment]
Hi @leomiquelutti, I have followed your steps using Google Collab and I am **not** able to reproduce this error. So I'm not sure what is happening.

This looks like Google Collab is trying to use an older version of pandas. What version of pandas is it using? Perhaps that can help us narrow things down.

`import pandas as pd`
`pd.__version__`

**Comment by leomiquelutti** [comment]
Hi @EvanBianco,

thanks for the reply. The pandas version is 1.3.5.

I wrote a reproducible version of my error in [this Google Colab](https://colab.research.google.com/drive/1Cs-QFbcdj06trytZbEDwU63_qgywW53-?usp=sharing). I kept the other packages' installs and imports and summarized my code down to the error point.

**Comment by EvanBianco** [comment]
Just to recap, 

`w.df(['DT', 'PHIE', 'RHOB', 'SW'])` works, but `w.df(['DT', 'PHIE', 'RHOB', 'SW', 'DT_DS'])` throws the Attribute Error. Note, that `w.df(['PHIE', 'RHOB', 'SW', 'DT_DS'])` also works. 

It's the use of `DT` and `DT_DS` together that causes grief.

I suspect what is happening here is when a despiked curve it calculated from the original and added to the well (`w.data['DT_DS']`) it gets the `key` in the `data` dictionary as you've defined it (`DT_DS`), **but** the mnemonic doesn't change. No meta data is changed it's just copied directly from `w.data['DT']`. My guess is that the mnemonics are being passed to pandas and not the keys (which would be unique), and it can't make two columns with the same name. Potential fix would be to set the default to do keys, and then have an option to use mnemonics. Leaving mnemonics as default means we'll encounter this non-uniqueness. Another fix would be to append suffixes to duplicate mnemonics, but this is less ideal. You'd end up with `DT` and `DT_2` in your DataFrame for instance, and lose the notion that you despiked it. 

Additionally, to cope with this I thought it would have just been a matter of changing the mnemonic of the `DT_DS` Curve to something unique, like `DT-DS`. But, when I do:

`w.data['DT_DS'].mnemonic = 'DT_DS'`

I get an `AttributeError: can't set attribute`. This is worrying for a different reason because this is not something that caused problems before, IIRC.

In sum: I see issues here: 
1) how do we want to handle the `w.df()` method when dealing with derivative curves / duplicate mnemonics?, and 
2) When did setting a mnemonic stop working? Because if you can do 2 then you can't really deal with 1.

I'll ping @kwinkunks here to bring it to his attention. If I'm misunderstanding something please let me know. Thanks again @leomiquelutti for the nice example.

**Comment by kwinkunks** [comment]
The fundamental issue is that there are essentially 2 names for every curve -- the unique key in `well.data` and the non-unique `curve.mnemonic`. 

Potentially `df()` could take either keys or mnemonics, e.g. taking an argument to specify which. Then if it's mnemonics check that they are unique (keys are guaranteed unique).

I don't think it should be impossible to have two curves with the same mnemonic, but possibly there should be a dual index with some uniquifier ('version' or whatever).

I'm a bit surprised this hasn't been a problem before... thank you @leomiquelutti for raising it!
